/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.greatcattle.jui.main;

import com.greatcattle.business.consts.Msg;
import com.greatcattle.business.service.LoginService;
import com.greatcattle.framework.ContextApplication;
import com.greatcattle.framework.utils.SpringUtils;
import com.greatcattle.utils.StrTools;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Administrator
 */
public class LoginFrm extends javax.swing.JFrame {
    /**
     * Creates new form LoginFrm
     */
    public LoginFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomePanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        pwdLabel = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        loginInBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("loginFrm"); // NOI18N
        setResizable(false);

        welcomePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "欢迎登陆", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 2, 24))); // NOI18N
        welcomePanel.setName("welcomePanel"); // NOI18N

        logoLabel.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/greatcattle/jui/img/resizeApi (2).png"))); // NOI18N
        logoLabel.setText("巨牛衡器软件管理系统");

        userNameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/greatcattle/jui/img/userName.png"))); // NOI18N
        userNameLabel.setText("用户名：");

        pwdLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/greatcattle/jui/img/password.png"))); // NOI18N
        pwdLabel.setText("密  码：");

        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userNameChange(evt);
            }
        });

        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdChange(evt);
            }
        });

        loginInBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/greatcattle/jui/img/login.png"))); // NOI18N
        loginInBtn.setText("登陆");
        loginInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginInBtnActionPerformed(evt);
            }
        });

        resetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/greatcattle/jui/img/reset.png"))); // NOI18N
        resetBtn.setText("重置");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(loginInBtn)
                .addGap(96, 96, 96)
                .addComponent(resetBtn)
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                        .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userNameLabel)
                            .addComponent(pwdLabel))
                        .addGap(18, 18, 18)
                        .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(password))
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                        .addComponent(logoLabel)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                        .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pwdLabel)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetBtn)
                    .addComponent(loginInBtn))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(welcomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(welcomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginInBtnActionPerformed
        Map lgParam = new HashMap();
        LoginService loginService = SpringUtils.getBean(LoginService.class);
        lgParam.put("user_code", this.username.getText());
        String passWord = new String(this.password.getPassword());
        lgParam.put("pass_word", passWord);
        String retCode = loginService.loginIn(lgParam);
        if(!StrTools.isEqual(retCode, Msg.Succ.getCode())){
            this.errorLabel.setText(Msg.getMsg(retCode));
        }else{
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(false);// 本窗口隐藏,
                MainFrm mainFrm = new MainFrm();
                mainFrm.setVisible(true);
                mainFrm.setLocationRelativeTo(null);
                dispose();//本窗口销毁,释放内存资源
            }
        });
        }
    }//GEN-LAST:event_loginInBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
       password.setText(null);
       username.setText(null);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void userNameChange(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameChange
        this.errorLabel.setText(null);
    }//GEN-LAST:event_userNameChange

    private void pwdChange(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdChange
        this.errorLabel.setText(null);
    }//GEN-LAST:event_pwdChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        
        ContextApplication.initCtx();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginFrm loginFrm = new LoginFrm();
                loginFrm.setVisible(true);
                loginFrm.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton loginInBtn;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel pwdLabel;
    private javax.swing.JButton resetBtn;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField username;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
